package entities;
// Generated Jul 10, 2014 9:41:15 PM by Hibernate Tools 3.6.0



/**
 * ChitiethoadonId generated by hbm2java
 */
public class ChitiethoadonId  implements java.io.Serializable {


     private int mahoadon;
     private int masanpham;

    public ChitiethoadonId() {
    }

    public ChitiethoadonId(int mahoadon, int masanpham) {
       this.mahoadon = mahoadon;
       this.masanpham = masanpham;
    }
   
    public int getMahoadon() {
        return this.mahoadon;
    }
    
    public void setMahoadon(int mahoadon) {
        this.mahoadon = mahoadon;
    }
    public int getMasanpham() {
        return this.masanpham;
    }
    
    public void setMasanpham(int masanpham) {
        this.masanpham = masanpham;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChitiethoadonId) ) return false;
		 ChitiethoadonId castOther = ( ChitiethoadonId ) other; 
         
		 return (this.getMahoadon()==castOther.getMahoadon())
 && (this.getMasanpham()==castOther.getMasanpham());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMahoadon();
         result = 37 * result + this.getMasanpham();
         return result;
   }   


}


