package entities;
// Generated Jul 10, 2014 9:41:15 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Chitiethoadon generated by hbm2java
 */
public class Chitiethoadon  implements java.io.Serializable {


     private ChitiethoadonId id;
     private Sanpham sanpham;
     private Hoadon hoadon;
     private BigDecimal gia;
     private BigDecimal soluong;

    public Chitiethoadon() {
    }

	
    public Chitiethoadon(ChitiethoadonId id, Sanpham sanpham, Hoadon hoadon) {
        this.id = id;
        this.sanpham = sanpham;
        this.hoadon = hoadon;
    }
    public Chitiethoadon(ChitiethoadonId id, Sanpham sanpham, Hoadon hoadon, BigDecimal gia, BigDecimal soluong) {
       this.id = id;
       this.sanpham = sanpham;
       this.hoadon = hoadon;
       this.gia = gia;
       this.soluong = soluong;
    }
   
    public ChitiethoadonId getId() {
        return this.id;
    }
    
    public void setId(ChitiethoadonId id) {
        this.id = id;
    }
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }
    public Hoadon getHoadon() {
        return this.hoadon;
    }
    
    public void setHoadon(Hoadon hoadon) {
        this.hoadon = hoadon;
    }
    public BigDecimal getGia() {
        return this.gia;
    }
    
    public void setGia(BigDecimal gia) {
        this.gia = gia;
    }
    public BigDecimal getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(BigDecimal soluong) {
        this.soluong = soluong;
    }




}


