package entities;
// Generated Jul 10, 2014 9:41:15 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Danhmuc generated by hbm2java
 */
public class Danhmuc  implements java.io.Serializable {


     private int madanhmuc;
     private String tendanhmuc;
     private Set sanphams = new HashSet(0);

    public Danhmuc() {
    }

	
    public Danhmuc(int madanhmuc) {
        this.madanhmuc = madanhmuc;
    }
    public Danhmuc(int madanhmuc, String tendanhmuc, Set sanphams) {
       this.madanhmuc = madanhmuc;
       this.tendanhmuc = tendanhmuc;
       this.sanphams = sanphams;
    }
   
    public int getMadanhmuc() {
        return this.madanhmuc;
    }
    
    public void setMadanhmuc(int madanhmuc) {
        this.madanhmuc = madanhmuc;
    }
    public String getTendanhmuc() {
        return this.tendanhmuc;
    }
    
    public void setTendanhmuc(String tendanhmuc) {
        this.tendanhmuc = tendanhmuc;
    }
    public Set getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set sanphams) {
        this.sanphams = sanphams;
    }




}


