package entities;
// Generated Jul 10, 2014 9:41:15 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Sanpham generated by hbm2java
 */
public class Sanpham  implements java.io.Serializable {


     private int masanpham;
     private Danhmuc danhmuc;
     private String tensanpham;
     private BigDecimal gia;
     private BigDecimal soluong;
     private String tinhtrang;
     private String mota;
     private BigDecimal ngaysanxuat;
     private String hinhanh;
     private Set chitiethoadons = new HashSet(0);

    public Sanpham() {
    }

	
    public Sanpham(int masanpham) {
        this.masanpham = masanpham;
    }
    public Sanpham(int masanpham, Danhmuc danhmuc, String tensanpham, BigDecimal gia, BigDecimal soluong, String tinhtrang, String mota, BigDecimal ngaysanxuat, String hinhanh, Set chitiethoadons) {
       this.masanpham = masanpham;
       this.danhmuc = danhmuc;
       this.tensanpham = tensanpham;
       this.gia = gia;
       this.soluong = soluong;
       this.tinhtrang = tinhtrang;
       this.mota = mota;
       this.ngaysanxuat = ngaysanxuat;
       this.hinhanh = hinhanh;
       this.chitiethoadons = chitiethoadons;
    }
   
    public int getMasanpham() {
        return this.masanpham;
    }
    
    public void setMasanpham(int masanpham) {
        this.masanpham = masanpham;
    }
    public Danhmuc getDanhmuc() {
        return this.danhmuc;
    }
    
    public void setDanhmuc(Danhmuc danhmuc) {
        this.danhmuc = danhmuc;
    }
    public String getTensanpham() {
        return this.tensanpham;
    }
    
    public void setTensanpham(String tensanpham) {
        this.tensanpham = tensanpham;
    }
    public BigDecimal getGia() {
        return this.gia;
    }
    
    public void setGia(BigDecimal gia) {
        this.gia = gia;
    }
    public BigDecimal getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(BigDecimal soluong) {
        this.soluong = soluong;
    }
    public String getTinhtrang() {
        return this.tinhtrang;
    }
    
    public void setTinhtrang(String tinhtrang) {
        this.tinhtrang = tinhtrang;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public BigDecimal getNgaysanxuat() {
        return this.ngaysanxuat;
    }
    
    public void setNgaysanxuat(BigDecimal ngaysanxuat) {
        this.ngaysanxuat = ngaysanxuat;
    }
    public String getHinhanh() {
        return this.hinhanh;
    }
    
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }
    public Set getChitiethoadons() {
        return this.chitiethoadons;
    }
    
    public void setChitiethoadons(Set chitiethoadons) {
        this.chitiethoadons = chitiethoadons;
    }




}


