package entities;
// Generated Jul 23, 2014 7:06:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Categorizetable generated by hbm2java
 */
public class Categorizetable  implements java.io.Serializable {


     private String categorizeTableId;
     private String description;
     private Set tableTs = new HashSet(0);

    public Categorizetable() {
    }

	
    public Categorizetable(String categorizeTableId, String description) {
        this.categorizeTableId = categorizeTableId;
        this.description = description;
    }
    public Categorizetable(String categorizeTableId, String description, Set tableTs) {
       this.categorizeTableId = categorizeTableId;
       this.description = description;
       this.tableTs = tableTs;
    }
   
    public String getCategorizeTableId() {
        return this.categorizeTableId;
    }
    
    public void setCategorizeTableId(String categorizeTableId) {
        this.categorizeTableId = categorizeTableId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getTableTs() {
        return this.tableTs;
    }
    
    public void setTableTs(Set tableTs) {
        this.tableTs = tableTs;
    }




}


